name: Expressions & Context

on: 
  push:
    branches:
      - "feature*"
  pull_request:
  issues:

run-name: "Expressions & Context by @${{github.actor}}, event: ${{github.event_name}}"

jobs:
  using-Expressions-and-Context:
    runs-on: ubuntu-latest
    steps:
      - name: Expressions
        id: Expressions
        run: |
          echo ${{1}}
          echo ${{'This is a string'}}
          echo  ${{ github.repository_id }}
          echo ${{ github.repository }}
          echo $${{1>2}}
      - name: Dump Context
        run: |
          echo '${{ toJson(github)}}'
          echo '${{ toJson(job)}}'
          echo '${{ toJson(secrets)}}'
          echo '${{ toJson(steps)}}'
          echo '${{ toJson(runner)}}'
      - name: 
        if: ${{github.action == 'BrunoRoman'}}
        run: echo "actor correto"