name: Expressions Context
on: [push, issues]
run-name: "Expressions & COntext by @{{ github.actor }}, event: ${{ github.event_name }}"

jobs:
  using-espressions:
    runs-on: ubuntu-latest
    steps:
      - name: Expressions
        id: Expressions
        run: |
          echo ${{ null }}
          echo ${{ 1 > 2 }}
          echo ${{ true || (false && true ) }}
      - name: Context
        id: Context
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(runner) }}'
          echo '${{ toJson(steps) }}'
