name: Manually Trigger
on: 
  workflow_dispatch: 
    inputs:
      string:
        description: A string inputt
        type: string
        required: true
        default: "Default value"
      option:
        description: "Anoption input"
        type: choice
        default: "Option 3"
        options:
          - Option 1
          - Option 2
          - Option 3


jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REF
      - run: |
          echo "string: ${{ inputs.string }}"
          echo "Option: ${{ inputs.option }}"
