name: Workflow COmmands
on: 
  - push

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting a error message
        run: echo "::error::Missing semicolon"
      - name: Setting a error message with param
        run: echo "::error title:Error title,file=app.js,line=2,endLine-3,col=5,endColumn=7::Missing Semicolon"
